services:
  db:
    image: postgres:latest
    container_name: saigonride-db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=tt314
      - POSTGRES_DB=SaigonRideDB
    ports:
      - "5432:5432"
    networks:
      - saigonride-network

  app:
    image: saigonride-app
    build:
      context: .
      dockerfile: Dockerfile
    container_name: saigonride-web
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Host=db;Database=SaigonRideDB;Username=postgres;Password=tt314
    ports:
      - "5000:8080"
    depends_on:
      - db
    networks:
      - saigonride-network

networks:
  saigonride-network:
    driver: bridge
